### ISSUE TITLE
TypeError: this.log is not a function

### ISSUE THREAD

**Issue by balamuruganvasudevan** [hms-networks/node-red-contrib-kolibri#2]
Hi,

While deploying the flow which contains kolibri node, getting the below error. Any help would be appreciated.

4 Aug 03:58:22 - [info] Starting flows
4 Aug 03:58:22 - [info] Started flows
4 Aug 03:58:24 - [red] Uncaught Exception:
4 Aug 03:58:24 - TypeError: this.log is not a function
    at KolibriConsumer.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-red-contrib-kolibri\nodes\kolibri-broker.js:123:26)
    at KolibriConsumer.emit (events.js:315:20)
    at WebSocket.KolibriConsumer.wsOnError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-red-contrib-kolibri\lib\consumer.js:87:18)
    at WebSocket.emit (events.js:315:20)
    at ClientRequest.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-red-contrib-kolibri\node_modules\ws\lib\websocket.js:551:15)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by arbue** [comment]
@balamuruganvasudevan Thanks for reporting this issue. Its fixed in the 0.2.2 version.
